// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: blog-post.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32     `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string  `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       *BlogPost `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostResponse) Reset() {
	*x = BlogPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostResponse) ProtoMessage() {}

func (x *BlogPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostResponse.ProtoReflect.Descriptor instead.
func (*BlogPostResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{0}
}

func (x *BlogPostResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostResponse) GetData() *BlogPost {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlogPostStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32    `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       bool     `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostStatusResponse) Reset() {
	*x = BlogPostStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostStatusResponse) ProtoMessage() {}

func (x *BlogPostStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostStatusResponse.ProtoReflect.Descriptor instead.
func (*BlogPostStatusResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{1}
}

func (x *BlogPostStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostStatusResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostStatusResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type BlogPostListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32       `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string    `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       []*BlogPost `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostListResponse) Reset() {
	*x = BlogPostListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostListResponse) ProtoMessage() {}

func (x *BlogPostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostListResponse.ProtoReflect.Descriptor instead.
func (*BlogPostListResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{2}
}

func (x *BlogPostListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostListResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostListResponse) GetData() []*BlogPost {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlogPostPagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BlogPost         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Meta  *PaginationMetadata `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *BlogPostPagination) Reset() {
	*x = BlogPostPagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostPagination) ProtoMessage() {}

func (x *BlogPostPagination) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostPagination.ProtoReflect.Descriptor instead.
func (*BlogPostPagination) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{3}
}

func (x *BlogPostPagination) GetItems() []*BlogPost {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BlogPostPagination) GetMeta() *PaginationMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BlogPostPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32               `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string            `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       *BlogPostPagination `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostPaginationResponse) Reset() {
	*x = BlogPostPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostPaginationResponse) ProtoMessage() {}

func (x *BlogPostPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostPaginationResponse.ProtoReflect.Descriptor instead.
func (*BlogPostPaginationResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{4}
}

func (x *BlogPostPaginationResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostPaginationResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostPaginationResponse) GetData() *BlogPostPagination {
	if x != nil {
		return x.Data
	}
	return nil
}

type FindAllPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *FindAllPostRequest) Reset() {
	*x = FindAllPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPostRequest) ProtoMessage() {}

func (x *FindAllPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPostRequest.ProtoReflect.Descriptor instead.
func (*FindAllPostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllPostRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindAllPostRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FindOnePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOnePostRequest) Reset() {
	*x = FindOnePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOnePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOnePostRequest) ProtoMessage() {}

func (x *FindOnePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOnePostRequest.ProtoReflect.Descriptor instead.
func (*FindOnePostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{6}
}

func (x *FindOnePostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// findBySlug
type FindBySlugPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *FindBySlugPostRequest) Reset() {
	*x = FindBySlugPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBySlugPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBySlugPostRequest) ProtoMessage() {}

func (x *FindBySlugPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBySlugPostRequest.ProtoReflect.Descriptor instead.
func (*FindBySlugPostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{7}
}

func (x *FindBySlugPostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug        string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary     string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	IsPublish   bool   `protobuf:"varint,3,opt,name=isPublish,proto3" json:"isPublish,omitempty"`
	PublishDate string `protobuf:"bytes,4,opt,name=PublishDate,proto3" json:"PublishDate,omitempty"`
	AuthorId    uint32 `protobuf:"varint,5,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreatePostRequest) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *CreatePostRequest) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

func (x *CreatePostRequest) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug        string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary     string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	IsPublish   bool   `protobuf:"varint,4,opt,name=isPublish,proto3" json:"isPublish,omitempty"`
	PublishDate string `protobuf:"bytes,5,opt,name=PublishDate,proto3" json:"PublishDate,omitempty"`
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdatePostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdatePostRequest) GetIsPublish() bool {
	if x != nil {
		return x.IsPublish
	}
	return false
}

func (x *UpdatePostRequest) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

type DeletePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePostRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_blog_post_proto protoreflect.FileDescriptor

var file_blog_post_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x1a, 0x09, 0x64, 0x74,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x16, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x71, 0x0a, 0x14, 0x42, 0x6c,
	0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x69, 0x0a,
	0x12, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x1a, 0x42, 0x6c, 0x6f,
	0x67, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12,
	0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x3e, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x53, 0x6c, 0x75, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x9d, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x32, 0xdd,
	0x03, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x51, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x1d, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65,
	0x12, 0x1d, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x20, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x53,
	0x6c, 0x75, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70,
	0x6f, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36,
	0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x6d, 0x69, 0x74, 0x68, 0x69, 0x77, 0x61, 0x74,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x42,
	0x08, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x01, 0x5a, 0x09, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_post_proto_rawDescOnce sync.Once
	file_blog_post_proto_rawDescData = file_blog_post_proto_rawDesc
)

func file_blog_post_proto_rawDescGZIP() []byte {
	file_blog_post_proto_rawDescOnce.Do(func() {
		file_blog_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_post_proto_rawDescData)
	})
	return file_blog_post_proto_rawDescData
}

var file_blog_post_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blog_post_proto_goTypes = []interface{}{
	(*BlogPostResponse)(nil),           // 0: blog_post.BlogPostResponse
	(*BlogPostStatusResponse)(nil),     // 1: blog_post.BlogPostStatusResponse
	(*BlogPostListResponse)(nil),       // 2: blog_post.BlogPostListResponse
	(*BlogPostPagination)(nil),         // 3: blog_post.BlogPostPagination
	(*BlogPostPaginationResponse)(nil), // 4: blog_post.BlogPostPaginationResponse
	(*FindAllPostRequest)(nil),         // 5: blog_post.FindAllPostRequest
	(*FindOnePostRequest)(nil),         // 6: blog_post.FindOnePostRequest
	(*FindBySlugPostRequest)(nil),      // 7: blog_post.FindBySlugPostRequest
	(*CreatePostRequest)(nil),          // 8: blog_post.CreatePostRequest
	(*UpdatePostRequest)(nil),          // 9: blog_post.UpdatePostRequest
	(*DeletePostRequest)(nil),          // 10: blog_post.DeletePostRequest
	(*BlogPost)(nil),                   // 11: dto.BlogPost
	(*PaginationMetadata)(nil),         // 12: common.PaginationMetadata
}
var file_blog_post_proto_depIdxs = []int32{
	11, // 0: blog_post.BlogPostResponse.data:type_name -> dto.BlogPost
	11, // 1: blog_post.BlogPostListResponse.data:type_name -> dto.BlogPost
	11, // 2: blog_post.BlogPostPagination.items:type_name -> dto.BlogPost
	12, // 3: blog_post.BlogPostPagination.meta:type_name -> common.PaginationMetadata
	3,  // 4: blog_post.BlogPostPaginationResponse.data:type_name -> blog_post.BlogPostPagination
	5,  // 5: blog_post.BlogPostService.findAll:input_type -> blog_post.FindAllPostRequest
	6,  // 6: blog_post.BlogPostService.findOne:input_type -> blog_post.FindOnePostRequest
	7,  // 7: blog_post.BlogPostService.findBySlug:input_type -> blog_post.FindBySlugPostRequest
	8,  // 8: blog_post.BlogPostService.create:input_type -> blog_post.CreatePostRequest
	9,  // 9: blog_post.BlogPostService.update:input_type -> blog_post.UpdatePostRequest
	10, // 10: blog_post.BlogPostService.delete:input_type -> blog_post.DeletePostRequest
	4,  // 11: blog_post.BlogPostService.findAll:output_type -> blog_post.BlogPostPaginationResponse
	0,  // 12: blog_post.BlogPostService.findOne:output_type -> blog_post.BlogPostResponse
	0,  // 13: blog_post.BlogPostService.findBySlug:output_type -> blog_post.BlogPostResponse
	0,  // 14: blog_post.BlogPostService.create:output_type -> blog_post.BlogPostResponse
	1,  // 15: blog_post.BlogPostService.update:output_type -> blog_post.BlogPostStatusResponse
	1,  // 16: blog_post.BlogPostService.delete:output_type -> blog_post.BlogPostStatusResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_blog_post_proto_init() }
func file_blog_post_proto_init() {
	if File_blog_post_proto != nil {
		return
	}
	file_dto_proto_init()
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostPagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOnePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBySlugPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_post_proto_goTypes,
		DependencyIndexes: file_blog_post_proto_depIdxs,
		MessageInfos:      file_blog_post_proto_msgTypes,
	}.Build()
	File_blog_post_proto = out.File
	file_blog_post_proto_rawDesc = nil
	file_blog_post_proto_goTypes = nil
	file_blog_post_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogPostServiceClient is the client API for BlogPostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogPostServiceClient interface {
	FindAll(ctx context.Context, in *FindAllPostRequest, opts ...grpc.CallOption) (*BlogPostPaginationResponse, error)
	FindOne(ctx context.Context, in *FindOnePostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error)
	FindBySlug(ctx context.Context, in *FindBySlugPostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error)
	Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error)
	Update(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*BlogPostStatusResponse, error)
	Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*BlogPostStatusResponse, error)
}

type blogPostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogPostServiceClient(cc grpc.ClientConnInterface) BlogPostServiceClient {
	return &blogPostServiceClient{cc}
}

func (c *blogPostServiceClient) FindAll(ctx context.Context, in *FindAllPostRequest, opts ...grpc.CallOption) (*BlogPostPaginationResponse, error) {
	out := new(BlogPostPaginationResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/findAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostServiceClient) FindOne(ctx context.Context, in *FindOnePostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error) {
	out := new(BlogPostResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/findOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostServiceClient) FindBySlug(ctx context.Context, in *FindBySlugPostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error) {
	out := new(BlogPostResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/findBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostServiceClient) Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*BlogPostResponse, error) {
	out := new(BlogPostResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostServiceClient) Update(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*BlogPostStatusResponse, error) {
	out := new(BlogPostStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostServiceClient) Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*BlogPostStatusResponse, error) {
	out := new(BlogPostStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_post.BlogPostService/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogPostServiceServer is the server API for BlogPostService service.
type BlogPostServiceServer interface {
	FindAll(context.Context, *FindAllPostRequest) (*BlogPostPaginationResponse, error)
	FindOne(context.Context, *FindOnePostRequest) (*BlogPostResponse, error)
	FindBySlug(context.Context, *FindBySlugPostRequest) (*BlogPostResponse, error)
	Create(context.Context, *CreatePostRequest) (*BlogPostResponse, error)
	Update(context.Context, *UpdatePostRequest) (*BlogPostStatusResponse, error)
	Delete(context.Context, *DeletePostRequest) (*BlogPostStatusResponse, error)
}

// UnimplementedBlogPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogPostServiceServer struct {
}

func (*UnimplementedBlogPostServiceServer) FindAll(context.Context, *FindAllPostRequest) (*BlogPostPaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (*UnimplementedBlogPostServiceServer) FindOne(context.Context, *FindOnePostRequest) (*BlogPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedBlogPostServiceServer) FindBySlug(context.Context, *FindBySlugPostRequest) (*BlogPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBySlug not implemented")
}
func (*UnimplementedBlogPostServiceServer) Create(context.Context, *CreatePostRequest) (*BlogPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBlogPostServiceServer) Update(context.Context, *UpdatePostRequest) (*BlogPostStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBlogPostServiceServer) Delete(context.Context, *DeletePostRequest) (*BlogPostStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBlogPostServiceServer(s *grpc.Server, srv BlogPostServiceServer) {
	s.RegisterService(&_BlogPostService_serviceDesc, srv)
}

func _BlogPostService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).FindAll(ctx, req.(*FindAllPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOnePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).FindOne(ctx, req.(*FindOnePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostService_FindBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBySlugPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).FindBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/FindBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).FindBySlug(ctx, req.(*FindBySlugPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).Create(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).Update(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post.BlogPostService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostServiceServer).Delete(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogPostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog_post.BlogPostService",
	HandlerType: (*BlogPostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "findAll",
			Handler:    _BlogPostService_FindAll_Handler,
		},
		{
			MethodName: "findOne",
			Handler:    _BlogPostService_FindOne_Handler,
		},
		{
			MethodName: "findBySlug",
			Handler:    _BlogPostService_FindBySlug_Handler,
		},
		{
			MethodName: "create",
			Handler:    _BlogPostService_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _BlogPostService_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _BlogPostService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog-post.proto",
}
