// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: blog-post-stat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogPostStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32         `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string      `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       *BlogPostStat `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostStatResponse) Reset() {
	*x = BlogPostStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_stat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostStatResponse) ProtoMessage() {}

func (x *BlogPostStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_stat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostStatResponse.ProtoReflect.Descriptor instead.
func (*BlogPostStatResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_stat_proto_rawDescGZIP(), []int{0}
}

func (x *BlogPostStatResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostStatResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostStatResponse) GetData() *BlogPostStat {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlogPostStatStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32    `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       bool     `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostStatStatusResponse) Reset() {
	*x = BlogPostStatStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_stat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostStatStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostStatStatusResponse) ProtoMessage() {}

func (x *BlogPostStatStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_stat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostStatStatusResponse.ProtoReflect.Descriptor instead.
func (*BlogPostStatStatusResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_stat_proto_rawDescGZIP(), []int{1}
}

func (x *BlogPostStatStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostStatStatusResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostStatStatusResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type UpdateBlogPostStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CountType StatCountType `protobuf:"varint,2,opt,name=countType,proto3,enum=dto.StatCountType" json:"countType,omitempty"`
}

func (x *UpdateBlogPostStatRequest) Reset() {
	*x = UpdateBlogPostStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_stat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBlogPostStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogPostStatRequest) ProtoMessage() {}

func (x *UpdateBlogPostStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_stat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogPostStatRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogPostStatRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_stat_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBlogPostStatRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBlogPostStatRequest) GetCountType() StatCountType {
	if x != nil {
		return x.CountType
	}
	return StatCountType_VIEW_INCREASE
}

var File_blog_post_stat_proto protoreflect.FileDescriptor

var file_blog_post_stat_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x2d, 0x73, 0x74, 0x61, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x1a, 0x09, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x75, 0x0a, 0x14, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x1a, 0x42, 0x6c, 0x6f, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x5d, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67,
	0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x30, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x32, 0x78, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x29, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3a, 0x0a, 0x1d, 0x63,
	0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x6d, 0x69, 0x74, 0x68, 0x69, 0x77, 0x61, 0x74, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x42, 0x0c, 0x42, 0x6c,
	0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x50, 0x01, 0x5a, 0x09, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_post_stat_proto_rawDescOnce sync.Once
	file_blog_post_stat_proto_rawDescData = file_blog_post_stat_proto_rawDesc
)

func file_blog_post_stat_proto_rawDescGZIP() []byte {
	file_blog_post_stat_proto_rawDescOnce.Do(func() {
		file_blog_post_stat_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_post_stat_proto_rawDescData)
	})
	return file_blog_post_stat_proto_rawDescData
}

var file_blog_post_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blog_post_stat_proto_goTypes = []interface{}{
	(*BlogPostStatResponse)(nil),       // 0: blog_post_stat.BlogPostStatResponse
	(*BlogPostStatStatusResponse)(nil), // 1: blog_post_stat.BlogPostStatStatusResponse
	(*UpdateBlogPostStatRequest)(nil),  // 2: blog_post_stat.UpdateBlogPostStatRequest
	(*BlogPostStat)(nil),               // 3: dto.BlogPostStat
	(StatCountType)(0),                 // 4: dto.StatCountType
}
var file_blog_post_stat_proto_depIdxs = []int32{
	3, // 0: blog_post_stat.BlogPostStatResponse.data:type_name -> dto.BlogPostStat
	4, // 1: blog_post_stat.UpdateBlogPostStatRequest.countType:type_name -> dto.StatCountType
	2, // 2: blog_post_stat.BlogPostStatService.update:input_type -> blog_post_stat.UpdateBlogPostStatRequest
	1, // 3: blog_post_stat.BlogPostStatService.update:output_type -> blog_post_stat.BlogPostStatStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blog_post_stat_proto_init() }
func file_blog_post_stat_proto_init() {
	if File_blog_post_stat_proto != nil {
		return
	}
	file_dto_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_post_stat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_stat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostStatStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_stat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBlogPostStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_post_stat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_post_stat_proto_goTypes,
		DependencyIndexes: file_blog_post_stat_proto_depIdxs,
		MessageInfos:      file_blog_post_stat_proto_msgTypes,
	}.Build()
	File_blog_post_stat_proto = out.File
	file_blog_post_stat_proto_rawDesc = nil
	file_blog_post_stat_proto_goTypes = nil
	file_blog_post_stat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogPostStatServiceClient is the client API for BlogPostStatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogPostStatServiceClient interface {
	Update(ctx context.Context, in *UpdateBlogPostStatRequest, opts ...grpc.CallOption) (*BlogPostStatStatusResponse, error)
}

type blogPostStatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogPostStatServiceClient(cc grpc.ClientConnInterface) BlogPostStatServiceClient {
	return &blogPostStatServiceClient{cc}
}

func (c *blogPostStatServiceClient) Update(ctx context.Context, in *UpdateBlogPostStatRequest, opts ...grpc.CallOption) (*BlogPostStatStatusResponse, error) {
	out := new(BlogPostStatStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_post_stat.BlogPostStatService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogPostStatServiceServer is the server API for BlogPostStatService service.
type BlogPostStatServiceServer interface {
	Update(context.Context, *UpdateBlogPostStatRequest) (*BlogPostStatStatusResponse, error)
}

// UnimplementedBlogPostStatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogPostStatServiceServer struct {
}

func (*UnimplementedBlogPostStatServiceServer) Update(context.Context, *UpdateBlogPostStatRequest) (*BlogPostStatStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterBlogPostStatServiceServer(s *grpc.Server, srv BlogPostStatServiceServer) {
	s.RegisterService(&_BlogPostStatService_serviceDesc, srv)
}

func _BlogPostStatService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogPostStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostStatServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post_stat.BlogPostStatService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostStatServiceServer).Update(ctx, req.(*UpdateBlogPostStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogPostStatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog_post_stat.BlogPostStatService",
	HandlerType: (*BlogPostStatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "update",
			Handler:    _BlogPostStatService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog-post-stat.proto",
}
