// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: blog-tag.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32    `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       *BlogTag `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogTagResponse) Reset() {
	*x = BlogTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogTagResponse) ProtoMessage() {}

func (x *BlogTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogTagResponse.ProtoReflect.Descriptor instead.
func (*BlogTagResponse) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{0}
}

func (x *BlogTagResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogTagResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogTagResponse) GetData() *BlogTag {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlogTagStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32    `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       bool     `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogTagStatusResponse) Reset() {
	*x = BlogTagStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogTagStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogTagStatusResponse) ProtoMessage() {}

func (x *BlogTagStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogTagStatusResponse.ProtoReflect.Descriptor instead.
func (*BlogTagStatusResponse) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{1}
}

func (x *BlogTagStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogTagStatusResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogTagStatusResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type BlogTagListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32      `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string   `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       []*BlogTag `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogTagListResponse) Reset() {
	*x = BlogTagListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogTagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogTagListResponse) ProtoMessage() {}

func (x *BlogTagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogTagListResponse.ProtoReflect.Descriptor instead.
func (*BlogTagListResponse) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{2}
}

func (x *BlogTagListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogTagListResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogTagListResponse) GetData() []*BlogTag {
	if x != nil {
		return x.Data
	}
	return nil
}

type FindAllTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortType SortByType `protobuf:"varint,1,opt,name=sortType,proto3,enum=dto.SortByType" json:"sortType,omitempty"`
}

func (x *FindAllTagRequest) Reset() {
	*x = FindAllTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTagRequest) ProtoMessage() {}

func (x *FindAllTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTagRequest.ProtoReflect.Descriptor instead.
func (*FindAllTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllTagRequest) GetSortType() SortByType {
	if x != nil {
		return x.SortType
	}
	return SortByType_ALPHABET_ASC
}

type FindOneTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOneTagRequest) Reset() {
	*x = FindOneTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneTagRequest) ProtoMessage() {}

func (x *FindOneTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneTagRequest.ProtoReflect.Descriptor instead.
func (*FindOneTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{4}
}

func (x *FindOneTagRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTagRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_tag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_tag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_tag_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTagRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_blog_tag_proto protoreflect.FileDescriptor

var file_blog_tag_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x1a, 0x09, 0x64, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x63, 0x0a, 0x15, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x67, 0x54,
	0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54,
	0x61, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x46, 0x69,
	0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x32, 0xf3, 0x02, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x12, 0x1b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x1b, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74,
	0x61, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x6c, 0x6f,
	0x67, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x74, 0x61,
	0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x54, 0x61, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x0a, 0x1c, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x61, 0x6d, 0x69, 0x74, 0x68, 0x69, 0x77, 0x61, 0x74, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x61, 0x67, 0x42, 0x07, 0x42, 0x6c, 0x6f, 0x67, 0x54,
	0x61, 0x67, 0x50, 0x01, 0x5a, 0x09, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blog_tag_proto_rawDescOnce sync.Once
	file_blog_tag_proto_rawDescData = file_blog_tag_proto_rawDesc
)

func file_blog_tag_proto_rawDescGZIP() []byte {
	file_blog_tag_proto_rawDescOnce.Do(func() {
		file_blog_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_tag_proto_rawDescData)
	})
	return file_blog_tag_proto_rawDescData
}

var file_blog_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_blog_tag_proto_goTypes = []interface{}{
	(*BlogTagResponse)(nil),       // 0: blog_tag.BlogTagResponse
	(*BlogTagStatusResponse)(nil), // 1: blog_tag.BlogTagStatusResponse
	(*BlogTagListResponse)(nil),   // 2: blog_tag.BlogTagListResponse
	(*FindAllTagRequest)(nil),     // 3: blog_tag.FindAllTagRequest
	(*FindOneTagRequest)(nil),     // 4: blog_tag.FindOneTagRequest
	(*CreateTagRequest)(nil),      // 5: blog_tag.CreateTagRequest
	(*UpdateTagRequest)(nil),      // 6: blog_tag.UpdateTagRequest
	(*DeleteTagRequest)(nil),      // 7: blog_tag.DeleteTagRequest
	(*BlogTag)(nil),               // 8: dto.BlogTag
	(SortByType)(0),               // 9: dto.SortByType
}
var file_blog_tag_proto_depIdxs = []int32{
	8, // 0: blog_tag.BlogTagResponse.data:type_name -> dto.BlogTag
	8, // 1: blog_tag.BlogTagListResponse.data:type_name -> dto.BlogTag
	9, // 2: blog_tag.FindAllTagRequest.sortType:type_name -> dto.SortByType
	3, // 3: blog_tag.BlogTagService.findAll:input_type -> blog_tag.FindAllTagRequest
	4, // 4: blog_tag.BlogTagService.findOne:input_type -> blog_tag.FindOneTagRequest
	5, // 5: blog_tag.BlogTagService.create:input_type -> blog_tag.CreateTagRequest
	6, // 6: blog_tag.BlogTagService.update:input_type -> blog_tag.UpdateTagRequest
	7, // 7: blog_tag.BlogTagService.delete:input_type -> blog_tag.DeleteTagRequest
	2, // 8: blog_tag.BlogTagService.findAll:output_type -> blog_tag.BlogTagListResponse
	0, // 9: blog_tag.BlogTagService.findOne:output_type -> blog_tag.BlogTagResponse
	0, // 10: blog_tag.BlogTagService.create:output_type -> blog_tag.BlogTagResponse
	1, // 11: blog_tag.BlogTagService.update:output_type -> blog_tag.BlogTagStatusResponse
	1, // 12: blog_tag.BlogTagService.delete:output_type -> blog_tag.BlogTagStatusResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blog_tag_proto_init() }
func file_blog_tag_proto_init() {
	if File_blog_tag_proto != nil {
		return
	}
	file_dto_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogTagStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogTagListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_tag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_tag_proto_goTypes,
		DependencyIndexes: file_blog_tag_proto_depIdxs,
		MessageInfos:      file_blog_tag_proto_msgTypes,
	}.Build()
	File_blog_tag_proto = out.File
	file_blog_tag_proto_rawDesc = nil
	file_blog_tag_proto_goTypes = nil
	file_blog_tag_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogTagServiceClient is the client API for BlogTagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogTagServiceClient interface {
	FindAll(ctx context.Context, in *FindAllTagRequest, opts ...grpc.CallOption) (*BlogTagListResponse, error)
	FindOne(ctx context.Context, in *FindOneTagRequest, opts ...grpc.CallOption) (*BlogTagResponse, error)
	Create(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*BlogTagResponse, error)
	Update(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*BlogTagStatusResponse, error)
	Delete(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*BlogTagStatusResponse, error)
}

type blogTagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogTagServiceClient(cc grpc.ClientConnInterface) BlogTagServiceClient {
	return &blogTagServiceClient{cc}
}

func (c *blogTagServiceClient) FindAll(ctx context.Context, in *FindAllTagRequest, opts ...grpc.CallOption) (*BlogTagListResponse, error) {
	out := new(BlogTagListResponse)
	err := c.cc.Invoke(ctx, "/blog_tag.BlogTagService/findAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogTagServiceClient) FindOne(ctx context.Context, in *FindOneTagRequest, opts ...grpc.CallOption) (*BlogTagResponse, error) {
	out := new(BlogTagResponse)
	err := c.cc.Invoke(ctx, "/blog_tag.BlogTagService/findOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogTagServiceClient) Create(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*BlogTagResponse, error) {
	out := new(BlogTagResponse)
	err := c.cc.Invoke(ctx, "/blog_tag.BlogTagService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogTagServiceClient) Update(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*BlogTagStatusResponse, error) {
	out := new(BlogTagStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_tag.BlogTagService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogTagServiceClient) Delete(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*BlogTagStatusResponse, error) {
	out := new(BlogTagStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_tag.BlogTagService/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogTagServiceServer is the server API for BlogTagService service.
type BlogTagServiceServer interface {
	FindAll(context.Context, *FindAllTagRequest) (*BlogTagListResponse, error)
	FindOne(context.Context, *FindOneTagRequest) (*BlogTagResponse, error)
	Create(context.Context, *CreateTagRequest) (*BlogTagResponse, error)
	Update(context.Context, *UpdateTagRequest) (*BlogTagStatusResponse, error)
	Delete(context.Context, *DeleteTagRequest) (*BlogTagStatusResponse, error)
}

// UnimplementedBlogTagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogTagServiceServer struct {
}

func (*UnimplementedBlogTagServiceServer) FindAll(context.Context, *FindAllTagRequest) (*BlogTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (*UnimplementedBlogTagServiceServer) FindOne(context.Context, *FindOneTagRequest) (*BlogTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedBlogTagServiceServer) Create(context.Context, *CreateTagRequest) (*BlogTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBlogTagServiceServer) Update(context.Context, *UpdateTagRequest) (*BlogTagStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBlogTagServiceServer) Delete(context.Context, *DeleteTagRequest) (*BlogTagStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBlogTagServiceServer(s *grpc.Server, srv BlogTagServiceServer) {
	s.RegisterService(&_BlogTagService_serviceDesc, srv)
}

func _BlogTagService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogTagServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_tag.BlogTagService/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogTagServiceServer).FindAll(ctx, req.(*FindAllTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogTagService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogTagServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_tag.BlogTagService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogTagServiceServer).FindOne(ctx, req.(*FindOneTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogTagService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogTagServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_tag.BlogTagService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogTagServiceServer).Create(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogTagService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogTagServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_tag.BlogTagService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogTagServiceServer).Update(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogTagService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogTagServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_tag.BlogTagService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogTagServiceServer).Delete(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogTagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog_tag.BlogTagService",
	HandlerType: (*BlogTagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "findAll",
			Handler:    _BlogTagService_FindAll_Handler,
		},
		{
			MethodName: "findOne",
			Handler:    _BlogTagService_FindOne_Handler,
		},
		{
			MethodName: "create",
			Handler:    _BlogTagService_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _BlogTagService_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _BlogTagService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog-tag.proto",
}
