// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: blog-post-section.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogPostSectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32            `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string         `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       *BlogPostSection `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostSectionResponse) Reset() {
	*x = BlogPostSectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostSectionResponse) ProtoMessage() {}

func (x *BlogPostSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostSectionResponse.ProtoReflect.Descriptor instead.
func (*BlogPostSectionResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{0}
}

func (x *BlogPostSectionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostSectionResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostSectionResponse) GetData() *BlogPostSection {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlogPostSectionStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32    `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Data       bool     `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BlogPostSectionStatusResponse) Reset() {
	*x = BlogPostSectionStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogPostSectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPostSectionStatusResponse) ProtoMessage() {}

func (x *BlogPostSectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPostSectionStatusResponse.ProtoReflect.Descriptor instead.
func (*BlogPostSectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{1}
}

func (x *BlogPostSectionStatusResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BlogPostSectionStatusResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BlogPostSectionStatusResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type FindOnePostSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOnePostSectionRequest) Reset() {
	*x = FindOnePostSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOnePostSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOnePostSectionRequest) ProtoMessage() {}

func (x *FindOnePostSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOnePostSectionRequest.ProtoReflect.Descriptor instead.
func (*FindOnePostSectionRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{2}
}

func (x *FindOnePostSectionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreatePostSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId      uint32          `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Pos         uint32          `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	ContentType PostContentType `protobuf:"varint,3,opt,name=contentType,proto3,enum=dto.PostContentType" json:"contentType,omitempty"`
	Content     string          `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreatePostSectionRequest) Reset() {
	*x = CreatePostSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePostSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostSectionRequest) ProtoMessage() {}

func (x *CreatePostSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostSectionRequest.ProtoReflect.Descriptor instead.
func (*CreatePostSectionRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostSectionRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostSectionRequest) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *CreatePostSectionRequest) GetContentType() PostContentType {
	if x != nil {
		return x.ContentType
	}
	return PostContentType_TEXT
}

func (x *CreatePostSectionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdatePostSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos     uint32 `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UpdatePostSectionRequest) Reset() {
	*x = UpdatePostSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostSectionRequest) ProtoMessage() {}

func (x *UpdatePostSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostSectionRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePostSectionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostSectionRequest) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *UpdatePostSectionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeletePostSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePostSectionRequest) Reset() {
	*x = DeletePostSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blog_post_section_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostSectionRequest) ProtoMessage() {}

func (x *DeletePostSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_post_section_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostSectionRequest.ProtoReflect.Descriptor instead.
func (*DeletePostSectionRequest) Descriptor() ([]byte, []int) {
	return file_blog_post_section_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostSectionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_blog_post_section_proto protoreflect.FileDescriptor

var file_blog_post_section_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x62, 0x6c, 0x6f, 0x67, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x64, 0x74,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x17, 0x42, 0x6c, 0x6f, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x1d, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2b, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x96,
	0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x32, 0xba, 0x03, 0x0a, 0x16,
	0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x4f, 0x6e,
	0x65, 0x12, 0x2c, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a,
	0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x69, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62, 0x6c, 0x6f, 0x67,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6c,
	0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x40, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x61, 0x6d, 0x69, 0x74, 0x68, 0x69, 0x77, 0x61, 0x74, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0f, 0x42, 0x6c,
	0x6f, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a,
	0x09, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_blog_post_section_proto_rawDescOnce sync.Once
	file_blog_post_section_proto_rawDescData = file_blog_post_section_proto_rawDesc
)

func file_blog_post_section_proto_rawDescGZIP() []byte {
	file_blog_post_section_proto_rawDescOnce.Do(func() {
		file_blog_post_section_proto_rawDescData = protoimpl.X.CompressGZIP(file_blog_post_section_proto_rawDescData)
	})
	return file_blog_post_section_proto_rawDescData
}

var file_blog_post_section_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_blog_post_section_proto_goTypes = []interface{}{
	(*BlogPostSectionResponse)(nil),       // 0: blog_post_section.BlogPostSectionResponse
	(*BlogPostSectionStatusResponse)(nil), // 1: blog_post_section.BlogPostSectionStatusResponse
	(*FindOnePostSectionRequest)(nil),     // 2: blog_post_section.FindOnePostSectionRequest
	(*CreatePostSectionRequest)(nil),      // 3: blog_post_section.CreatePostSectionRequest
	(*UpdatePostSectionRequest)(nil),      // 4: blog_post_section.UpdatePostSectionRequest
	(*DeletePostSectionRequest)(nil),      // 5: blog_post_section.DeletePostSectionRequest
	(*BlogPostSection)(nil),               // 6: dto.BlogPostSection
	(PostContentType)(0),                  // 7: dto.PostContentType
}
var file_blog_post_section_proto_depIdxs = []int32{
	6, // 0: blog_post_section.BlogPostSectionResponse.data:type_name -> dto.BlogPostSection
	7, // 1: blog_post_section.CreatePostSectionRequest.contentType:type_name -> dto.PostContentType
	2, // 2: blog_post_section.BlogPostSectionService.findOne:input_type -> blog_post_section.FindOnePostSectionRequest
	3, // 3: blog_post_section.BlogPostSectionService.create:input_type -> blog_post_section.CreatePostSectionRequest
	4, // 4: blog_post_section.BlogPostSectionService.update:input_type -> blog_post_section.UpdatePostSectionRequest
	5, // 5: blog_post_section.BlogPostSectionService.delete:input_type -> blog_post_section.DeletePostSectionRequest
	0, // 6: blog_post_section.BlogPostSectionService.findOne:output_type -> blog_post_section.BlogPostSectionResponse
	0, // 7: blog_post_section.BlogPostSectionService.create:output_type -> blog_post_section.BlogPostSectionResponse
	1, // 8: blog_post_section.BlogPostSectionService.update:output_type -> blog_post_section.BlogPostSectionStatusResponse
	1, // 9: blog_post_section.BlogPostSectionService.delete:output_type -> blog_post_section.BlogPostSectionStatusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blog_post_section_proto_init() }
func file_blog_post_section_proto_init() {
	if File_blog_post_section_proto != nil {
		return
	}
	file_dto_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blog_post_section_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostSectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_section_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogPostSectionStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_section_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOnePostSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_section_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePostSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_section_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blog_post_section_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blog_post_section_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_post_section_proto_goTypes,
		DependencyIndexes: file_blog_post_section_proto_depIdxs,
		MessageInfos:      file_blog_post_section_proto_msgTypes,
	}.Build()
	File_blog_post_section_proto = out.File
	file_blog_post_section_proto_rawDesc = nil
	file_blog_post_section_proto_goTypes = nil
	file_blog_post_section_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogPostSectionServiceClient is the client API for BlogPostSectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogPostSectionServiceClient interface {
	FindOne(ctx context.Context, in *FindOnePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionResponse, error)
	Create(ctx context.Context, in *CreatePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionResponse, error)
	Update(ctx context.Context, in *UpdatePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionStatusResponse, error)
	Delete(ctx context.Context, in *DeletePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionStatusResponse, error)
}

type blogPostSectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogPostSectionServiceClient(cc grpc.ClientConnInterface) BlogPostSectionServiceClient {
	return &blogPostSectionServiceClient{cc}
}

func (c *blogPostSectionServiceClient) FindOne(ctx context.Context, in *FindOnePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionResponse, error) {
	out := new(BlogPostSectionResponse)
	err := c.cc.Invoke(ctx, "/blog_post_section.BlogPostSectionService/findOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostSectionServiceClient) Create(ctx context.Context, in *CreatePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionResponse, error) {
	out := new(BlogPostSectionResponse)
	err := c.cc.Invoke(ctx, "/blog_post_section.BlogPostSectionService/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostSectionServiceClient) Update(ctx context.Context, in *UpdatePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionStatusResponse, error) {
	out := new(BlogPostSectionStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_post_section.BlogPostSectionService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogPostSectionServiceClient) Delete(ctx context.Context, in *DeletePostSectionRequest, opts ...grpc.CallOption) (*BlogPostSectionStatusResponse, error) {
	out := new(BlogPostSectionStatusResponse)
	err := c.cc.Invoke(ctx, "/blog_post_section.BlogPostSectionService/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogPostSectionServiceServer is the server API for BlogPostSectionService service.
type BlogPostSectionServiceServer interface {
	FindOne(context.Context, *FindOnePostSectionRequest) (*BlogPostSectionResponse, error)
	Create(context.Context, *CreatePostSectionRequest) (*BlogPostSectionResponse, error)
	Update(context.Context, *UpdatePostSectionRequest) (*BlogPostSectionStatusResponse, error)
	Delete(context.Context, *DeletePostSectionRequest) (*BlogPostSectionStatusResponse, error)
}

// UnimplementedBlogPostSectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogPostSectionServiceServer struct {
}

func (*UnimplementedBlogPostSectionServiceServer) FindOne(context.Context, *FindOnePostSectionRequest) (*BlogPostSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (*UnimplementedBlogPostSectionServiceServer) Create(context.Context, *CreatePostSectionRequest) (*BlogPostSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBlogPostSectionServiceServer) Update(context.Context, *UpdatePostSectionRequest) (*BlogPostSectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBlogPostSectionServiceServer) Delete(context.Context, *DeletePostSectionRequest) (*BlogPostSectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBlogPostSectionServiceServer(s *grpc.Server, srv BlogPostSectionServiceServer) {
	s.RegisterService(&_BlogPostSectionService_serviceDesc, srv)
}

func _BlogPostSectionService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOnePostSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostSectionServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post_section.BlogPostSectionService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostSectionServiceServer).FindOne(ctx, req.(*FindOnePostSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostSectionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostSectionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post_section.BlogPostSectionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostSectionServiceServer).Create(ctx, req.(*CreatePostSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostSectionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostSectionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post_section.BlogPostSectionService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostSectionServiceServer).Update(ctx, req.(*UpdatePostSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogPostSectionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogPostSectionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog_post_section.BlogPostSectionService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogPostSectionServiceServer).Delete(ctx, req.(*DeletePostSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogPostSectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog_post_section.BlogPostSectionService",
	HandlerType: (*BlogPostSectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "findOne",
			Handler:    _BlogPostSectionService_FindOne_Handler,
		},
		{
			MethodName: "create",
			Handler:    _BlogPostSectionService_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _BlogPostSectionService_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _BlogPostSectionService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog-post-section.proto",
}
