name: 'Pull request: Run unit test'

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v ./src/test